# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

utctime <- function(year, month, day, hour, min, sec, psec, repair = FALSE) {
    .Call('RcppDateTime_utctime', PACKAGE = 'RcppDateTime', year, month, day, hour, min, sec, psec, repair)
}

date_time_locale <- function() {
    .Call('RcppDateTime_date_time_locale', PACKAGE = 'RcppDateTime')
}

